# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0c85be84a29f73b62d279799fb880898a88d0999a0dcd18b3b07c717cb407a91a4836014712ccd51d19ef399a4729c5d50c1c8116d99b8cd7c92bb3179a9867

test:
  secret_key_base: 73c79f80b3e9ffb754310a8b85f6c1d86c57dfa2752455bb1b2fd52ad654a771b9424ce7f105c76d2fccffe5612668d29903b452f60f20aac614d61d774d5067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
